### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by MizzzViolet**
Fixed popup diagram UI

### CODE REVIEW

**Comment by PaddyHly** [comment]
Sequence editor doesn't have a background (inputs just float in place)
Drop-down menus in action editor and sequence editor are impossible to read (white on white until highlighted)

**Comment by MizzzViolet** [comment]
Oh yeah. Fixed.

**Comment by PaddyHly** [comment]
Still can't read drop-down on sequence editor, also debug is on.

**Comment by MizzzViolet** [comment]
Try now.

**Pull request merged**
