### PR TITLE
Swimlanes

### PR DESCRIPTION
**Pull request by seanlth**
Major changes to flowlanes. Need to add positional data to control structures. Required a lot of work to handle offsets for an arbitrary y level. This pull request also should fix the issue with getting the first node colour wrong.

### CODE REVIEW

**Comment by lukegrehan** [comment]
I get 

```
TypeError: lanesPerLevel[0] is undefined       flowlines.js:69:5
```

on an empty diagram

**Comment by lukegrehan** [comment]
Flow lines across branches don't merge properly

**Comment by seanlth** [comment]
Didn't he say he didn't want vertical lines?

**Comment by lukegrehan** [comment]
the yellow line shouldn't be going across the bottom line - it should divert up into the upper branch and out the other side. Likewise for the purple except it doesn't have the line across the bottom.

**Comment by PaddyHly** [comment]
Forks aren't handled correctly
diagram 1
diagram

**Comment by seanlth** [comment]
What's the issue with the bottom one?

**Comment by PaddyHly** [comment]
There should probably be a line from the beginning to the first bar and from the second bar to the end.

**Comment by seanlth** [comment]
Okay, shouldn't be too bad.

**Comment by PaddyHly** [comment]
For the top one the problem is with:

// found the array
if ( array.name == action.agent && array.y == action.yPixelPosition ) {
    foundAgentArray = true;
    index = i;
    break;
}

similar y doen't mean that they are part of the same branch

**Pull request merged**
